const ROUTES = {
  ROOT: "/",
  SIGNIN: '/signin',
  SIGNUP: '/signup',
  NOT_FOUND: '/404',
  CREATE: '/create',
  PLAN: '/plan',
  TO_WORK: '/to-work',
  EDIT_PLAN: '/edit-plan',
  VIDEOS: '/videos',
  PODCASTS: '/podcasts',
  COURSES: '/courses',
  TOOLKIT: '/toolkit',
  IDEA: '/idea',
  IDEA_PITCH: '/idea/pitch',
  IDEA_DESCRIPTION: '/idea/description',
  IDEA_SW: '/idea/strengths-and-weaknesses',
  STRATEGY: '/strategy',
  STRATEGY_VISION: '/strategy/vision',
  STRATEGY_MISSION: '/strategy/mission',
  STRATEGY_ACTION_PLAN: '/strategy/action-plan',
  MARKET_ANALYSIS: '/market-analysis',
  TARGET_GROUP_DETERMINATION: '/target-group-determination',
  PEOPLE_AND_ORGANISATION: '/people-and-organisation',
  MARKETING: '/marketing',
  FINANCIAL: '/financial',
  STARTUP: '/startup',
  ALL: '*',
};

export { ROUTES };
